# 1. -> YAML exercise
color: "red"
cup: "red"
glass: "green"
number: 30
five: 5
languagesIKnow:
  english: "very well"
  spanish: "kind of"
  german: "a little"
countToFive:
  - "one"
  - "two"
  - "three"
  - "6"
  - "7"
  - "8"

# 2. -> .travis.yml
language: node_js
node_js:
  - "20"
dist: focal
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    # Is it correct?
    - ../client/node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - npm run test

# 3. -> Github actions file: .github/workflows/deploy.yaml
name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.5.1"]

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
      redis:
        image: redis
        ports:
          - 6379:6379

    env:
      NODE_ENV: ci
      PORT: 3000

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps
          npm run build
      - name: Start server
        run: |
          nohup npm run start &
          sleep 3
      - name: Run tests
        run: npm run test
